In [1]:
import numpy as np
arr=np.array((1,2,3,4,5))
print(arr)

[1 2 3 4 5]


### Square brackes tells you the dimension

# 2D array


In [ ]:
#1d array whose elemets are a 2D array 

In [2]:
a=(3,2)
arr=np.zeros(a)
arr


array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [3]:
a=(3,2)
arr=np.ones(a)
arr


array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [8]:
np.linspace(3.0,4.0,num=7,retstep=True)
#spacing between sample 

(array([3.        , 3.16666667, 3.33333333, 3.5       , 3.66666667,
        3.83333333, 4.        ]),
 0.16666666666666666)

In [9]:
#num is the number of elements you want to be generated in the interval 
#endpoint is true, stop at the endpoint
#endpoint is false, go to the end then stop 

np.linspace(3.0,4.0,num=7,endpoint=False)

array([3.        , 3.14285714, 3.28571429, 3.42857143, 3.57142857,
       3.71428571, 3.85714286])

## Eye function

In [12]:
#reduced row echelon form
#Identity matrix 
#i, j, k 
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [13]:
np.eye(2,3)
#2 rows 3 columns

array([[1., 0., 0.],
       [0., 1., 0.]])

In [ ]:
# [low,high) inclusive and exclusive

In [15]:
import numpy as np 
from numpy import random 
#Genetate 6 numbers from 2 to 10, but not inclduing 10 
x=random.randint(2,10,6)
x

array([6, 9, 9, 7, 4, 2])

## Floating point numbers 

In [19]:
#rand() floating point numbers from unifrom distribution (0,1)
n=0
x=random.rand(n)
x

array([], dtype=float64)

In [21]:
x=random.randn(n)
x

array([], dtype=float64)

## Reshape 

In [24]:
arr=np.arange(12)
arr


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [26]:
newarr=arr.reshape(4,3)
newarr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

## Max and Min


In [36]:
arr=np.random.randint(2,20,25)
print(arr,'\n')
arr.max() #returns the maximum element 
arr.argmax() #returns the index of the maximum element


[11 13 19 16  7 16 17  8  3 10 18  3 16 11 14  8 16 13 16  5  8  5 18 16
 13] 



2

In [37]:
arr=np.random.randint(2,20,25)
print(arr)
arr.min()
arr.argmin()

[ 8  4  4 13 18  6  3 10 15 10 10  9 16  5  7 10 14 11 13 13 11  6  3  7
  2]


24

#### INDICES START AT 0

## Broadcasting 

In [40]:
arr=np.arange(1,20)
arr[0:4]=5
arr

array([ 5,  5,  5,  5,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

## Copying arrays 

In [42]:
y=arr.copy()

In [43]:
y

array([ 5,  5,  5,  5,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

## Boolean 

In [47]:
arr=np.arange(1,11)
bool_arr=arr>5
#Returns the numbers that are greater than 5 that are true 
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [48]:
#To do a conditional selction do, the values > 5

arr[bool_arr]


array([ 6,  7,  8,  9, 10])

In [49]:
#You can also do 
arr[arr>5]

array([ 6,  7,  8,  9, 10])

## Array operations 

In [51]:
arr*8
arr+8
arr/8


array([ 8, 16, 24, 32, 40, 48, 56, 64, 72, 80])

## Universal arrray functions 

In [53]:
np.sqrt(arr)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766])

In [52]:
np.exp(arr)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04])

In [56]:
np.sin(arr)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849, -0.54402111])

In [55]:
np.cos(arr)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219,
        0.96017029,  0.75390225, -0.14550003, -0.91113026, -0.83907153])

# Pandas 

In [59]:
import pandas as pd
my_data=[5,10,15]
pd.Series(data=my_data)


0     5
1    10
2    15
dtype: int64

In [61]:
labels={"a": 2, "b": 3, "c": 5}
pd.Series(data=my_data, index=labels)
#Default is alays 0 1 2, if the index is not indicated 

a     5
b    10
c    15
dtype: int64

In [62]:
ser1 = pd.Series([1, 2, 3, 4],
["Ghana", "USA", "Mexico", "Canada"])

In [63]:
ser1["Mexico"]

3

In [64]:
ser2 = pd.Series([10, 12, 7, 9], ["Ghana", "Brazil", "Mexico", "Nigeria"])

In [65]:
ser1 + ser2 # ser1 - ser2

Brazil      NaN
Canada      NaN
Ghana      11.0
Mexico     10.0
Nigeria     NaN
USA         NaN
dtype: float64

## Creating data frame 

In [74]:
from numpy.random import randn

np.random.seed(4) # 4 is a seed(can be any integer )
df = pd.DataFrame(data = randn(5,4),
index = ["A", "B", "C", "D", "E"],

columns = ["w", "x", "y", "z"])

df["w"]

A    0.050562
B   -0.418302
C    0.332250
D    0.425072
E   -0.606887
Name: w, dtype: float64

In [75]:
df[["w", "y"]]

w         y
A  0.050562 -0.995909
B -0.418302 -0.647707
C  0.332250  0.618670
D  0.425072 -1.156816
E -0.606887  0.723342

In [77]:
df["new"] = df["w"] + df["y"]

# Dropping


In [79]:
#df.drop(labels=None, axis=0, index=None, columns=None, level=None, inplace=False)
df.drop("new" , axis = 1, inplace = True)



In [80]:
df

w         x         y         z
A  0.050562  0.499951 -0.995909  0.693599
B -0.418302 -1.584577 -0.647707  0.598575
C  0.332250 -1.147477  0.618670 -0.087987
D  0.425072  0.332253 -1.156816  0.350997
E -0.606887  1.546979  0.723342  0.046136

## Axis 
- column =0 
- row=1 
- axis =0 
- axis =1

# Loc vs Iloc
- iloc needs the postion of the rows 
- loc needs column names 
