# Mark Ilodigwe
## Homework 2
### 2/5/24

## 1. Read in the data

In [5]:
!ls

DA0101EN-2-Review-Data-Wrangling.ipynb crime_incident_data2017.csv
HW2.pdf                                mark-ilodigwe-homework-2.ipynb
Pandus_Numpy_Continued .ipynb


In [1]:
import pandas as pd
import numpy as np
df=pd.read_csv("crime_incident_data2017.csv")
df.head(7)
number_of_rows=len(df)
print("The count of rows is ", number_of_rows)

The count of rows is  41032


In [2]:
df.dropna(axis=0, inplace=True)

df

Address Case Number Crime Against   Neighborhood  \
2          200 BLOCK OF SE 78TH AVE   17-900367      Property     Montavilla   
5      5400 BLOCK OF NE MALLORY AVE   17-900129      Property           King   
6         5000 BLOCK OF NE 19TH AVE   17-901079      Property         Vernon   
7         5000 BLOCK OF NE 19TH AVE   17-901079      Property         Vernon   
8         12000 BLOCK OF SE PINE ST   17-900253      Property      Hazelwood   
...                             ...         ...           ...            ...   
41026  10200 BLOCK OF NE SANDY BLVD   17-286419       Society       Parkrose   
41027   8800 BLOCK OF NE SANDY BLVD   17-285386       Society         Sumner   
41028     9700 BLOCK OF SE STARK ST   17-286082       Society      Hazelwood   
41029     9700 BLOCK OF SE STARK ST   17-286413       Society      Hazelwood   
41031  8000 BLOCK OF SE POWELL BLVD   17-286659       Society  Foster-Powell   

       Number of Records Occur Date Occur Month Year  Occur Time  \
2                      1    12/1/03          12/1/03         800   
5                      1   11/28/10          11/1/10        1612   
6                      1    11/8/13          11/1/13        1200   
7                      1    11/8/13          11/1/13        1200   
8                      1     1/6/14           1/1/14         805   
...                  ...        ...              ...         ...   
41026                  1    8/31/17           8/1/17        2005   
41027                  1    8/31/17           8/1/17         535   
41028                  1    8/31/17           8/1/17        1619   
41029                  1    8/31/17           8/1/17        1959   
41031                  1    8/31/17           8/1/17        2354   

             Offense Category  Offense Count  \
2              Fraud Offenses              1   
5              Fraud Offenses              1   
6              Fraud Offenses              1   
7              Fraud Offenses              1   
8              Fraud Offenses              1   
...                       ...            ...   
41026  Drug/Narcotic Offenses              1   
41027  Drug/Narcotic Offenses              1   
41028   Prostitution Offenses              1   
41029   Prostitution Offenses              1   
41031   Weapon Law Violations              1   

                                  Offense Type  Open Data Lat  Open Data Lon  \
2      False Pretenses/Swindle/Confidence Game        45.5207       -122.583   
5                               Identity Theft        45.5625       -122.664   
6      False Pretenses/Swindle/Confidence Game        45.5594       -122.646   
7                               Identity Theft        45.5594       -122.646   
8                        Credit Card/ATM Fraud        45.5204       -122.539   
...                                        ...            ...            ...   
41026                 Drug/Narcotic Violations        45.5591       -122.557   
41027                 Drug/Narcotic Violations        45.5554       -122.571   
41028                             Prostitution        45.5191       -122.563   
41029                             Prostitution        45.5191       -122.563   
41031                   Weapons Law Violations        45.4974       -122.580   

       Open Data X  Open Data Y Report Date Report Month Year  
2        7668150.0     682825.0      1/9/17            1/1/17  
5        7647987.0     698581.0      1/3/17            1/1/17  
6        7652567.0     697337.0     1/26/17            1/1/17  
7        7652567.0     697337.0     1/26/17            1/1/17  
8        7679522.0     682404.0      1/6/17            1/1/17  
...            ...          ...         ...               ...  
41026    7675224.0     696649.0     8/31/17            8/1/17  
41027    7671560.0     695399.0     8/31/17            8/1/17  
41028    7673292.0     682101.0     8/31/17            8/1/17  
41029    7673292.0     682101.0     8/31/17            8/1/17  
41031   

## 4. Search through the “Offense Type” column and “replace” any similar values with one consistent value.


In [3]:
df['Offense Type'].value_counts()

#df['z']=df['x','y','W']


Theft From Motor Vehicle                       6947
Motor Vehicle Theft                            4689
All Other Larceny                              4558
Vandalism                                      3863
Burglary                                       2824
Shoplifting                                    2259
Identity Theft                                 1794
Simple Assault                                 1216
Drug/Narcotic Violations                       1095
Theft of Motor Vehicle Parts or Accessories    1073
Intimidation                                    900
Theft From Building                             895
False Pretenses/Swindle/Confidence Game         870
Aggravated Assault                              839
Robbery                                         608
Counterfeiting/Forgery                          448
Weapons Law Violations                          266
Credit Card/ATM Fraud                           226
Arson                                           200
Prostitution

In [10]:
#Here, I used an if/elif serious to categorize the various subcategories of crimes in the dataaset. Theft had the most 
import pandas as pd

new_df = df.loc[:, ["Offense Type"]]

if not new_df.empty:
    for offense_type in new_df["Offense Type"]:
        if offense_type in ['Rape', 'Commercial Sex Acts', 'Sodomy', 'Pornography/Obscene Material', 'Sexual Assault With an Object', 'Assisting or Promoting Prostitution', 'Sexual Assault With An Object','Statutory Rape','Prostitution','Incest','Fondling']:
            new_df.loc[new_df["Offense Type"] == offense_type, "Offense Type"] = 'Overall Sex Crimes'
        elif offense_type in ['Theft From Motor Vehicle','All Other Larceny','Motor Vehicle Theft','Vandalism','Burglary','Shoplifting','Identity Theft','Theft of Motor Vehicle Parts or Accessories','Theft From Building','False Pretenses/Swindle/Confidence Game','Pocket-Picking','Purse-Snatching','Embezzlement','Stolen Property Offenses','Robbery']:
            new_df.loc[new_df["Offense Type"] == offense_type, "Offense Type"] = 'Overall Theft'
        elif offense_type in ['Counterfeiting/Forgery',  'Credit Card/ATM Fraud','Theft From Coin-Operated Machine or Device','Wire Fraud', 'Welfare Fraud']:
            new_df.loc[new_df["Offense Type"] == offense_type, "Offense Type"]='Money Laundering of some kind'
        elif offense_type in ['Simple Assault', 'Intimidation', 'Aggravated Assault','Kidnapping/Abduction','Impersonation','Involuntary Servitude','Murder and Non-negligent Manslaughter','Extortion/Blackmail', 'Animal Cruelty']:
            new_df.loc[new_df["Offense Type"] == offense_type, "Offense Type"]='Person on Person/Animal crime'
        elif offense_type in ['Drug Equipment Violations', 'Drug/Narcotic Violations', 'Weapons Law Violations', 'Arson', 'Hacking/Computer Invasion']:
            new_df.loc[new_df["Offense Type"] == offense_type, "Offense Type"]='Person  used object to commit crimes'

    print(new_df.value_counts())



Offense Type                        
Overall Theft                           30693
Person on Person/Animal crime            3006
Person  used object to commit crimes     1586
Money Laundering of some kind             698
Overall Sex Crimes                        163
dtype: int64


In [11]:
new_df

Offense Type
2                             Overall Theft
5                             Overall Theft
6                             Overall Theft
7                             Overall Theft
8             Money Laundering of some kind
...                                     ...
41026  Person  used object to commit crimes
41027  Person  used object to commit crimes
41028                    Overall Sex Crimes
41029                    Overall Sex Crimes
41031  Person  used object to commit crimes

[36146 rows x 1 columns]

# 4. Search through the “Offense Type” column and “replace” any similar values with one consistent value.

What does this mean?




# 2. Linear Algebra, Matrices


In [41]:
B = np.array([[1, 3],
              [2, 4],
              [-3, -1]])

A = np.array([[2, 1, 2],
              [-5, 4, -1],
              [1, 5, 6]])

y = np.array([[2],
              [-4],
              [1]])


z= np.array([[-15],
              [-8],
              [-22]])

In [42]:
#BA
A=A.reshape(3,3)
A

B=B.reshape(2,3)
B



#R-1 dimesnions for dimendion 
# in R3 but has 2D

array([[ 1,  3,  2],
       [ 4, -3, -1]])

In [43]:
z.ndim

2

In [44]:
#For equation 1: 
equation_1=np.dot(B,A)
equation_1


array([[-11,  23,  11],
       [ 22, -13,   5]])

In [45]:
#For equation 2: 
equation_2=np.dot(A,B.T )
equation_2

array([[  9,   3],
       [  5, -31],
       [ 28, -17]])

In [46]:
#For equation 3:

equation_3=np.matmul(A,y)
equation_3

array([[  2],
       [-27],
       [-12]])

In [47]:
#For equation 4: 

equation_4=np.matmul(y.T,z)
equation_4

array([[-20]])

In [53]:
#For equation 5:
equation_5=np.matmul(y,z.T)
equation_5

array([[-30, -16, -44],
       [ 60,  32,  88],
       [-15,  -8, -22]])